### PR TITLE
added: in-elastic, out-elastic, in-out-elastic

### PR DESCRIPTION
**Pull request by matthewmueller**
for some rubbery fun

### CODE REVIEW

**Comment by rauchg** [comment]
Where are the equations extracted from? We need a CREDITS section in the Readme as well

**Comment by matthewmueller** [comment]
they're from tween.js. it says in the file: https://github.com/component/ease/blob/master/index.js#L2

**Comment by rauchg** [comment]
We need to include their copyright as per their LICENSE, and also include their original copyright since they took them from

```
Easing equations Copyright (c) 2001 Robert Penner http://robertpenner.com/easing/
```

**Comment by matthewmueller** [comment]
good call, i think this should work.

**Comment by rauchg** [comment]
Thanks a lot @MatthewMueller

**Pull request merged**
